Fix bug on select
Fix bug if the selected item is not in the list of suggested values of a multiple suggest

Error: scope.$matches[index] is undefined
SelectFactory/$select.select/</<@http://localhost:3000/bower_components/angular-strap/dist/angular-strap.js:2507:17
SelectFactory/$select.select/<@http://localhost:3000/bower_components/angular-strap/dist/angular-strap.js:2506:40
...

The fix is not perfect because a "false" is displayed on the form initialization, an empty string is probably more appropriate