Angular 1.4.7 fix filter:notarray
When I switch from angular 1.3.15 to 1.4.7 i saw that i got error like this:

Error: [filter:notarray] Expected array but received: false

So i propose to add this simple fix to avoid it.

Best regards